name: CI (macOS)

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Restore
      run: |
        dotnet tool restore
        dotnet paket restore
    - name: Build
      run: dotnet fake run build.fsx
    - name: Test
      run: dotnet fake run build.fsx -t test
    - name: Pack
      run: dotnet fake run build.fsx -t pack
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts-macos
        path: artifacts/